version: '3.8'

services:
  # -------------------------
  # Servicio PostgreSQL
  # -------------------------
  pgserver:
    image: postgres:latest
    container_name: pgserver
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dbnet
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: soccernowdb
    restart: unless-stopped

  # -------------------------
  # Servicio Spring Boot
  # -------------------------
  springbootapp:
    image: myapp:latest
    container_name: java_app
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    depends_on:
      - pgserver
    ports:
      - "8080:8080"
    networks:
      - dbnet
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  dbnet:
    driver: bridge
